@startuml
' ============================================================
' DIAGRAMA DE ACTIVIDADES - PACIENTE EN URGENCIAS
' ============================================================

start

:Paciente llega a Urgencias;
:Administrativo resgistra datos y DNI;
:Sistema genera Numero de Historia;

:Enfermero hace el Triaje;
:Sistema calcula codigo de color;

if (¿Es urgencia critica?) then (Sí, ROJO)
  :Activar Alerta Sonora y Visual;
  :Asignar Box de reanimacion automaticamente;
else (AMARILLO/VERDE/BLANCO)
  :Calcular tiempo de espera;
  :Asignar cama segun especialidad;
endif

:Actualizar tablero central de camas;
:Paciente espera segun prioridad;

:Medico atiende al pacinte;
:Medico actualiza estado del paciente;

if (¿Necesita traslado a UCI?) then (Sí)
  :Verificar camas disponibles en otra area;
  :Coordinar traslado;
else (No)
  if (¿Estado = ALTA?) then (Sí)
    :Liberar la cama;
  else (No, GRAVE o ESTABLE)
    :Permanece en observacion;
  endif
endif

:Generar informe medico;
:Integrar informe en historia clinica;

stop
@enduml
